language: go

go:
  - tip # The latest version of Go.

git:
  depth: 3
  quiet: true

env:
  global:
    - MYAPP=gl2j-gw
    - MYEMAIL=dokshukin@gmail.com
    - BUILD_DATE=$(date "+%Y-%m-%d_%T")
    - secure: ${GITHUB_TOKEN}

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y upx

install:
  - go get -u github.com/dokshukin/$MYAPP
  - cd $GOPATH/src/github.com/dokshukin/$MYAPP
  - go install


# build the app,build the package
gobuild_args: -x -ldflags "-s -w -X main.version=${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} -X main.build=${BUILD_DATE}"
before_deploy:
  - mkdir -p build/{386,amd64}
  - GOOS=freebsd GOARCH=386   go build -o build/386/${MYAPP}_freebsd-386-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} *.go
  - GOOS=freebsd GOARCH=amd64 go build -o build/amd64/${MYAPP}_freebsd-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} *.go
  - GOOS=darwin  GOARCH=amd64 go build -o build/amd64/${MYAPP}_darwin-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} *.go
  - GOOS=linux   GOARCH=386   go build -o build/386/${MYAPP}_linux-386-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} *.go
  - GOOS=linux   GOARCH=amd64 go build -o build/amd64/${MYAPP}_linux-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER} *.go
  - upx build/386/${MYAPP}_linux-386-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
  - upx build/amd64/${MYAPP}_linux-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}


deploy:
  provider: releases
  email: ${MYEMAIL}
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - build/386/${MYAPP}_linux-386-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
    - build/amd64/${MYAPP}_linux-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
    - build/386/${MYAPP}_freebsd-386-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
    - build/amd64/${MYAPP}_freebsd-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
    - build/amd64/${MYAPP}_darwin-amd64-${TRAVIS_TAG}.${TRAVIS_BUILD_NUMBER}
  skip_cleanup: true
  on:
    tags: true
    branch: master
